namespace: morpheus

name: utilities

version: 1.0.0

readme: README.md

authors:
- CodetheThings <Chris@codethethings.com>

description: A collection of common utilities installed on the Morpheus CMP hosts to enable additional capabilities

license:
- GPL-2.0-or-later

license_file: ''

tags:
  - morpheus
  - utilities
  - cmp
  
dependencies: {}

# The URL of the originating SCM repository
repository: http://example.com/repository

# The URL to any online docs
documentation: http://docs.example.com

# The URL to the homepage of the collection/project
homepage: http://example.com

# The URL to the collection issue tracker
issues: http://example.com/issue/tracker
