---
- name: Install Local Package(s) for Morpheus
  hosts: all
  gather_facts: true
  become: true
  roles:
    - Terraform
    - azure_cli
    - gcp_sdk
    - powershell
    - terraform
    - vmware_powercli