---
- name: Import the Microsoft repository key and Create Azure CLI Repository
  ansible.builtin.yum_repository:
    name: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgcheck: yes
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install Azure CLI
  package:
    name:
      - azure-cli
    state: present

- name: Install PowerShellGet
  shell:
    cmd: |
      pwsh -c - << 'EOF'
      Install-Module -Name PowerShellGet -Force -Scope AllUsers
      EOF

- name: Install Az.Subscription
  shell:
    cmd: |
      pwsh -c - << 'EOF'
      Install-Module -Name az.subscription -allowprerelease -Force -Scope AllUsers
      EOF

- name: Install Partner Center CLI
  shell:
    cmd: |
      pwsh -c - << 'EOF'
      Install-Module -Name partnercenter -allowclobber -Force -Scope AllUsers
      EOF