---
- name: Configure PowerShell Repo
  shell: 'curl https://packages.microsoft.com/config/rhel/{{ansible_distribution_major_version}}/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo'

- name: Update package lists
  yum:
    update_cache: yes
  when: ansible_distribution_major_version == "7"

- name: Install PowerShell 7
  package:
    name:
      - powershell
    state: present