---
- name: Configure PowerShell Repo
  ansible.builtint.yum_repository:
    name: microsoft
    baseurl: "https://packages.microsoft.com/config/rhel/{{ansible_distribution_major_version}}/prod.repo"
    state: present

- name: Install PowerShell 7
  package:
    name:
      - powershell
    state: present