---
- name: Add Hashicorp Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add the HashiCorp Linux Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg allow-insecure=yes] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Update package lists
  apt:
    update_cache: yes

- name: Install Terraform
  package:
    name:
      - software-properties-common
      - gnupg
      - terraform
    state: present