---
- name: Import HashiCorp GPG Key
  command:
    cmd: |
      wget -O- https://apt.releases.hashicorp.com/gpg | \
      gpg --dearmor | \
      sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
  become: yes

- name: Add the HashiCorp Linux Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Update package lists
  apt:
    update_cache: yes

- name: Install Terraform
  package:
    name:
      - software-properties-common
      - gnupg
      - terraform
    state: present