---
- name: Add the HashiCorp Linux Repository
  ansible.builtin.yum_repository:
    name: hashicorp
    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    state: present

- name: Install Terraform
  package:
    name:
      - yum-utils
      - terraform
    state: present