- name: Add Ansible Repo
  ansible.builtin.apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present

- name: Update package lists
  apt:
    update_cache: yes

- name: Install Ansible
  package:
    name:
      - software-properties-common
      - ansible
    state: present