- name: Update package lists
  yum:
    update_cache: yes
  when: ansible_distribution_major_version == "7"

- name: Install PowerShell 7
  package:
    name:
      - epel-release
      - ansible
    state: present