---
- name: Download Cloud SDK Distro
  ansible.builtin.yum_repository:
    name: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: no
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present

- name: Install Google Cloud SDK
  package:
    name:
      - google-cloud-sdk
    state: present