---
- name: Download Cloud SDK Distro
  shell:
    cmd: |
      sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
      [google-cloud-sdk]
      name=Google Cloud SDK
      baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
             https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      EOM

- name: Update package lists
  yum:
    update_cache: yes
  when: ansible_distribution_major_version == "7"

- name: Install Google Cloud SDK
  package:
    name:
      - google-cloud-sdk
    state: present